# Generated by Django 3.2.12 on 2023-07-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order', models.CharField(max_length=48)),
                ('location', models.CharField(max_length=48)),
                ('delivery_options', models.CharField(max_length=48)),
                ('shipment_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_time', models.TimeField()),
            ],
        ),
    ]
