# Generated by Django 4.2.3 on 2023-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=48)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=48)),
                ('identification_number', models.CharField(max_length=48)),
            ],
        ),
    ]
